rename indiestor to indiestor-pro where applicable -- first draft attempt

diff --git a/src/usr/bin/indiestor-pro-watch-group b/src/usr/bin/indiestor-pro-watch-group
--- a/src/usr/bin/indiestor-pro-watch-group
+++ b/src/usr/bin/indiestor-pro-watch-group
@@ -1,6 +1,6 @@
 #!/bin/sh
 #------------------------------------------------------------
-# Indiestor program
+# Indiestor Pro program
 # Concept, requirements, specifications, and unit testing
 # By Alex Gardiner, alex@indiestor.com
 # Written by Erik Poupaert, erik@sankuru.biz
@@ -8,20 +8,26 @@
 # Licensed under the GPL
 #------------------------------------------------------------
 group=$1
+watchType=$2
 
 if [ "$group" = "" ] ; then
 	echo "group argument required" >&2 
 	exit 1
 fi
 
-groupFile="/var/spool/indiestor/$group"
-
-if [ ! -f $groupFile ]; then
-	touch $groupFile
-else
-	if [  "$(pgrep -f '/usr/bin/php /usr/share/indiestor-core/prg/indiestor-inotify.php')" = "" ] ; then
-		rm -f $groupFile
-		/usr/bin/touch $groupFile
-	fi
+if [ "$watchType" = "" ] ; then
+	echo "watchType argument required" >&2 
+	exit 1
 fi
+
+if [ "$watchType" = "main" ] ; then
+	events='attrib,move,move_self,create,delete,delete_self'
+else
+	events='modify'
+fi
+
+while indiestor-pro --group $group -show-watches $watchType | \
+		inotifywait --exclude __${group}__${watchType}__ --fromfile - --event $events; do
+	indiestor-pro-touch $group
+done
 
